### ISSUE TITLE
fused extra kv?

### ISSUE THREAD

**Issue by Xynonners** [SHI-Labs/NATTEN#132]
Hi there,

Would it be possible to achieve an extra KV on the fused op?

I am interested in using NATTEN with [Attention is Off by One](https://www.evanmiller.org/attention-is-off-by-one.html) but it seems the only way to do this currently is via the unfused op.

Thanks

**Comment by alihassanijr** [comment]
Thank you for your interest.

Yes it is possible; forward pass is relatively easy, but backward pass gets a little complicated.
I'll keep this issue open until I get a chance to implement them.

There might also be a way to do it without actually fusing the extra KV into the main kernel. I'll try and think about that too, because that might just be faster (i.e. in theory the Q cross extra KV could run with torch.sdpa).

**Comment by alihassanijr** [comment]
Might be a little late, but we're actually working on a solution to do this (it's the latter solution, where you can run FNA and any other form of attention on the same query tensor, and merge their attention results).

It's pretty straightforward to do, and is already being used in many projects for context parallelism.

I'll be opening a PR with this feature soon.

**Comment by alihassanijr** [comment]
Closing since feature merged into main. Feel free to reopen if there's any questions.
