### ISSUE TITLE
low version (<=0.14.6) not support large kernel size?

### ISSUE THREAD

**Issue by TongkunGuan** [SHI-Labs/NATTEN#133]
does not support kernel size 64?

**Comment by alihassanijr** [comment]
Unfortunately no.

Most unfused NATTEN kernels templated the kernel size argument, requiring it to be known at compile time, and just for the sake of more lightweight packages we limited those to kernel size 13 in earlier versions.

Since 0.16, when we introduced FNA, naive kernels can assume any kernel size, but that results in a performance regression (which is why we templated them).
However, FNA kernels can handle any kernel size without taking a toll on performance.

We highly recommend upgrading and using FNA instead. The only change required compared to 0.14.6 is using the new API.

Also to be clear, neighborhood attention is undefined with even window sizes (i.e. it would have to be 63 not 64).
