### ISSUE TITLE
Issues in windows with torch version 1.X.X.

### ISSUE THREAD

**Issue by KangHyunwoogi** [SHI-Labs/NATTEN#148]
Hello, alihassanijr, 
Thanks for providing NATTEN.

I'm having trouble building natten on Windows, but my pytorch version is 1.11 and don't want to upgrade my torch version to 2.X.X.
Is there any solution to build natten in case of torch version 1.X.X??

Thanks.

**Comment by alihassanijr** [comment]
Thank you; unfortunately we can't support all versions of torch, especially as older CUDA versions and architectures get deprecated, torch APIs changes, and the like.

Since building from source is the only option for Windows, you can try building it with an older torch build, but I highly suspect you'll run into issues with CUDA compatibility even if you override the checks on torch version.

You could revert back to our older versions though:

[This commit](https://github.com/SHI-Labs/NATTEN/tree/3036259bdc5c30b7b49fe8ba17d60a0ab0d780dd) is the only one I know supports Windows, and torch 1.8 and above (NATTEN never supported older torch versions).
But note it's very old, and only has our naive backend, and no FNA.

**Comment by alihassanijr** [comment]
The issue appears to be resolved, so closing now. Feel free to reopen if you still have questions.
