### ISSUE TITLE
How to perform NA only at specific locations

### ISSUE THREAD

**Issue by PengfeiRen96** [SHI-Labs/NATTEN#151]
Excellent Work！If I only need to perform NA at some specific locations (the number of these points is much less than the number of tokens on the feature map), does the current NA operation support this function? If it is supported, how can I implement this function?

**Comment by alihassanijr** [comment]
Thank you for your interest;

Unfortunately NATTEN does not support very fine-grained patterns such as that, and they will be difficult to get very performant kernels out of.

It is however relatively easy to just construct an attention mask and use FMHA for that. If you expect there to be a few tokens that attend locally, and the rest are still doing self attention, you're definitely better off just using an attention mask because it's near impossible to get any efficiency gain from that pattern (at least as far as I can tell.)

**Comment by alihassanijr** [comment]
The issue appears to be resolved, so closing now. Feel free to reopen if you still have questions.
