### ISSUE TITLE
Does not support kernel sizes greater than 13

### ISSUE THREAD

**Issue by xravitejax** [SHI-Labs/NATTEN#16]
natten2dqkrpb_cuda_forward is not supporting kernel sizes greater than 13. The maximum kernel size it works for is 13. Is this expected ?

```
>>> import torch
>>> from natten import NeighborhoodAttention2D
>>> 
>>> na2d = NeighborhoodAttention2D(dim=128, kernel_size=15, dilation=2, num_heads=2)
>>> na2d = na2d.to('cuda:0')
>>> 
>>> x = torch.randn(4, 256, 256, 128)
>>> x = x.to('cuda:0')
>>> 
>>> y = na2d(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/natten/natten2d.py", line 63, in forward
    attn = natten2dqkrpb(q, k, self.rpb, dilation)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/natten/functional.py", line 145, in natten2dqkrpb
    return NATTEN2DQKRPBFunction.apply(query, key, rpb, dilation)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py", line 118, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/natten/functional.py", line 90, in forward
    attn = _C.natten2dqkrpb_forward(
RuntimeError: natten2dqkrpb_cuda_forward does not support kernel size 15

```

**Comment by alihassanijr** [comment]
Hello and thank you for your interest in NATTEN.

No, unfortunately the current build's CUDA backend does not implement 2D kernel sizes larger than 13x13.
There are a couple of reasons for that: 
1. Increase in kernel sizes result in significant latency increases, therefore larger kernels were hard to even test.
2. In our 2D NA, we introduce a tiled variant that is enabled for head_dim=32, but that variant (because of the shortcomings of the implementation) can only handle up to kernel size 13x13. 

That said, larger kernel sizes can be "enabled" by adding the templates; the problem will be that those larger kernel sizes won't run the tiled algorithm, so you should expect them to be really slow. And they tend to eat up a lot of memory.

For most use cases, we typically recommend doing smaller kernels and varying dilations to both maintain the efficiency and memory footprint, and get a good performance boost (as in [DiNAT](https://arxiv.org/abs/2209.15001)).

If despite all that, you still need a larger kernel, I'd be happy to branch out and add larger kernel support with the shortcoming I mentioned.

**Comment by xravitejax** [comment]
Hi,

Thanks for the prompt reply. 

Yes for most use cases stacking a combination of smaller kernels and varying dilations would suffice. For a very small set of use cases such as cross attention between two image feature maps, larger kernel sizes would be helpful.

However, given that it is memory intensive and slow I don't think its worth the extra effort. 

Thanks again for this amazing repo.

**Comment by alihassanijr** [comment]
Happy to help; thanks for the interest.

I would note that we do plan to add features to this repository, so it is by no means complete as it is right now.
So larger kernels will eventually be supported, once we can guarantee a reasonable speed.
