### ISSUE TITLE
MacOS install issue.

### ISSUE THREAD

**Issue by BentJams** [SHI-Labs/NATTEN#188]
I am not great with Terminal, but I have followed [these instructions](https://pytorch.org/get-started/locally/#macos-version) several times, tried installing Pip3 or Anaconda to manage installs, but after many reinstall attempts, still getting the same error message when I try to verify with:

import torch
x = torch.rand(5, 3)
print(x)

I get the error

(base) Mac:~ bentjams$ import torch
-bash: import: command not found
(base) Mac:~ bentjams$ x = torch.rand(5, 3)
-bash: syntax error near unexpected token `('
(base) Mac:~ bentjams$ print(x)
-bash: syntax error near unexpected token `x'
(base) Mac:~ bentjams$ 

Prior to this I was following [these instructions](https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#apple-mac-silicon) to install ComfyUI on MacOS Apple Silicon 

Any ideas?

Thank you :)

**Comment by BentJams** [comment]
Also this may help in diagnosing?

(base) Mac:~ bentjams$ python3 main.py
python3: can't open file '/Users/bentjams/main.py': [Errno 2] No such file or directory
(base) Mac:~ bentjams$ cd ComfyUI
(base) Mac:ComfyUI bentjams$ python3 main.py
Traceback (most recent call last):
  File "/Users/bentjams/ComfyUI/main.py", line 89, in <module>
    import comfy.utils
  File "/Users/bentjams/ComfyUI/comfy/utils.py", line 24, in <module>
    import safetensors.torch
ModuleNotFoundError: No module named 'safetensors'
(base) Mac:ComfyUI bentjams$

**Comment by alihassanijr** [comment]
You need to start an interactive python process to run python, otherwise you're executing commands like `import torch` in your shell instead of python. That's all of the errors in the OP.

In your second post, first you're trying to run a file that doesn't exist, then hit import errors because you don't have `safetensors` installed.

I'm just not finding what's relevant to NATTEN here, so I'm closing this issue and with respect would advise you to use the many tools available online to debug such issues.

**Comment by BentJams** [comment]
My apologies Ali, total newbie so I wasn't sure where else to look, a google search for a solution led me here. I will continue looking, appreciate your time in responding thank you.
