### ISSUE TITLE
Causality

### ISSUE THREAD

**Issue by MultiTrickFox** [SHI-Labs/NATTEN#20]
Great project and implementation! 
A good feature addition would be causality;
it seems like it's already implemented (the rightmost edge pixel only looking at values before it) so if only this operation was accessible through python, it would be a good use case.

**Comment by alihassanijr** [comment]
Hello and thanks for your interest.

To clarify, do you mean you'd expect every token to attend to a window ending at said token's position, instead of the token being centered?
For example, token 0 attends to itself, token 1 attends to 0 and 1, and token x attends to x - kernel_size + 1, x - kernel_size + 2, ..., x?

**Comment by MultiTrickFox** [comment]
Yes thats exactly what I meant

**Comment by alihassanijr** [comment]
Okay, so it might be easy to implement if we don't target the Tiled NA algorithm. Reconfiguring that might take a bit of time since it's all intertwined a bit.
However implementing this in the naive kernels, especially since I believe your primary focus is 1D (tokens) and not 2D (pixels), is probably easy, at least that's what I think at the moment.
We factored out the "neighborhood" logic into a "commons" file in both the CPU and GPU kernels. Modifying that, or just having an alternative would implement what you're asking (I don't at the moment foresee any roadblocks.)

That said, I might not have time to implement this in the coming weeks so I'll just keep the issue open.

**Comment by MultiTrickFox** [comment]
Yes my use case is mainly for 1D. I will look into this, thank you

**Comment by alihassanijr** [comment]
Causal masking added in #111 .
