### ISSUE TITLE
Support for bf16 fp16

### ISSUE THREAD

**Issue by jimmie33** [SHI-Labs/NATTEN#37]
~~Hi, I cannot find any information about the support for bf16 and fp16. Does the current library support any of them?~~

I found the information in the catalog. Then when is bf16 going to be supported?

**Comment by alihassanijr** [comment]
Thanks for your interest.

We will be updating NATTEN in the near future with new kernels that can easily support half and bfloat16.
The current set of kernels are relatively difficult to maintain and will eventually be phased out in favor of the new kernels.

However, it's important to note that lower-precision doesn't necessarily yield improved latency, especially when dealing with a memory-bound problem, an instance of which is neighborhood attention in its current implementation.
That said, it is possible to get around the memory bound by reformulating neighborhood attention, which is an ongoing effort, and for that we'd have to ask you for more patience.

**Comment by jonmorton** [comment]
> It's important to note that lower-precision doesn't necessarily yield improved latency, especially when dealing with a memory-bound problem

This seems counter-intuitive to me. Shouldn't fp16/bf16 use half the memory bandwidth as full precision floats? I thought this was the primary benefit of lowering precision.

**Comment by alihassanijr** [comment]
>This seems counter-intuitive to me. Shouldn't fp16/bf16 use half the memory bandwidth as full precision floats? I thought this was the primary benefit of lowering precision.

Not exactly; Simply changing data types doesn't make that much of a difference unless you're doing coalesced reads/writes.
Lowering precision isn't just about memory bandwidth; in certain cases you can also vectorize math ops.
Memory bound problems are therefore less likely to see as large of an improvement as compute-bound problems.

In short; you can never make assumptions about how big of an improvement in latency you will see with lower-precision without taking the problem itself into account.
To give an example, a pure matrix multiplication (with 128-bit alignment) is likely to accelerate even beyond 5X in latency in 16-bit precision, compared to 32-bit.
But the same cannot be said about say a vector-matrix multiplication (i.e. depthwise conv.)

In addition, neighborhood attention is only defined for odd-sized kernels (so that queries can be centered.)
This results in attention weights having an odd-sized contiguous dimension, which results in a memory alignment challenge that especially slows down reading from and writing to the attention tensor (and by extension its gradient.)

Putting all of this aside, we're actually working on a new release that will include a completely new set of kernels (which are GEMM-based and will therefore run on TensorCores for the first time), as well as the current ones, and I think I can fold bfloat16 into the workload. 
The primary challenge with having both bfloat16 and half in our previous releases was the code-base; it would just need a lot of duplication to handle the differences between float16 and bfloat16. In our upcoming release we're refactoring a lot of that, so adding in bfloat16 is just a lot simpler.

I can't really specify a date yet, but we're hoping to push out the new release this weekend or early next week.

**Comment by jimmie33** [comment]
@alihassanijr Thank you for the explanation. I have done some speed comparison between NATTEN's neighborhood attention and xformer's global self attention operators. I find that the neighborhood attention isn't faster even with a 3x3 window, but much more memory intensive.

Will the new updates improve that?

**Comment by alihassanijr** [comment]
@jimmie33 that is very much typical and expected, because you're effectively comparing latency, not compute, when the underlying algorithms are different.

There's multiple factors to consider:
* Xformers is using Flash Attention
  * Flash Attention is almost always going to be faster and more memory efficient than BMM attention (you can check their paper on what the contributing factors are).
  * BMM attention, or more generally non-fused attention was the standard practice until FMHA and FlashAttention.
  * Neighborhood attention is not yet fused.
* NATTEN is only comprised on **naive CUDA kernels**, with the exception of only the QK operator for 2D problems with 32 dimensions per head.
  * Naive kernels are not at all optimized and very rarely reach better occupancy compared optimized kernels.
  * No optimization means:
    * No use of shared memory
    * No coalesced reads
    * The underlying math is done in SIMT-style -- meaning they do all of their dot products on CUDA cores and do not utilize Tensor Cores
    * And the like...
  * Problem size matters: if you even use dim=31, NATTEN will not use the tiled kernels and occupancy drops.
 

To answer your question, the new updates will improve that.

For starters, we'll have GEMM-based kernels that are by definition highly optimized:
* They use an unmodified GEMM mainloop from CUTLASS:
  * Will use Tensor Cores
  * By extension will pre-fetch tiles into shared memory through coalesced asynchronous reads
 
They will support (almost) arbitrary problem sizes, meaning whether you use dim=32 or not, whether you use NA1D or NA2D, and regardless of the OP (QK, AV, or the gradient kernels), you will get a significant improvement in occupancy.

However, there are a few limits to the new release:
* There is a memory alignment challenge, which I'll honestly get into only if someone asks.
  * Because of this, you will probably see little to no difference in latency between tf32 and fp16/bf16.
  * Essentially, while everything will be faster, the difference between half and full precision will become minimal.
* It is still unfused -- meaning it's still going to be an unfair comparison to fused kernels.
* Only SM80 and above will be supported,
* 3D is not yet implemented (I honestly don't know if I'll have time to do it this round.)

Here's a sneak preview of the improvements the ops themselves are likely going to see (on A100):
![image](https://github.com/SHI-Labs/NATTEN/assets/68103095/4f0baea1-f530-4021-b0af-8327b421deab)



We are planning on another release in which we would implement a fused Neighborhood Attention.
That version will not only resolve the memory alignment challenge, it --will-- either match or improve upon the latency from doing self attention with Flash Attention / FMHA (at least in 1D).

The theory of it all is near-complete; implementation is complicated and time-consuming, and I've been very busy the past few months with classes, teaching, other research projects, and an internship, so that's essentially the primary bottleneck.

That said, our commitment to improving NATTEN has not changed, and we still have more interesting updates coming up which should enhance latency and memory usage significantly, and allow for easier extension/integration of NA into other packages.

**Comment by jimmie33** [comment]
Great to know all these details and the future plan. Nice work and I am looking forward to the new updates!

**Comment by ecilay** [comment]
Would you mind explain a bit on this:
`But the same cannot be said about say a vector-matrix multiplication (i.e. depthwise conv.)`

**Comment by alihassanijr** [comment]
@ecilay Yes.

Compute-bound problems, a perfect example of which is GEMMs, will naturally yield massive latency improvements in lower-precision settings.
Memory-bound problems do not necessarily follow the same pattern because a considerable ratio of their latency is due to memory bandwidth limits, and not computation (threads may sit idle waiting for data to process.)

Neighborhood attention operations are all broken into vector-matrix multiplications, and is a memory-bound problem; each query token has its own neighboring set of key tokens, therefore any CTA computing the output for that query requires to load one vector (query) and a matrix (keys), compute their dot products, store the output, and advance to the next query, at which point it needs to reload both another vector and a new matrix. Locality can help, but the implementation gets more complicated; meaning you can organize your threadblock swizzling function in a way that queries with overlapping neighborhoods are processed by the same thread or threadblock, so that the intersecting neighbors are loaded just once, and therefore reducing the number of global reads.

This does not take away the fact that this is still a vector-matrix multiplication, and therefore cannot natively run on Tensor Cores, which would limit the kernels to doing SIMT-style math ops.

The new implicit GEMM kernels we released get around this by computing "extra" attention weights, because it's actually favorable to doing SIMT-style instructions. The way it's done is that both the swizzling is designed to ensure locality, and for any possible query and key tiles, they are technically cross-attended, which, when carefully selecting the tile size, is a superset of neighborhood attention weights. We then just discard the "out-of-neighborhood" weights and store the correct ones into global memory.
