### ISSUE TITLE
NA with a mask for the tensor？

### ISSUE THREAD

**Issue by yifanlu0227** [SHI-Labs/NATTEN#39]
Thanks for your great work! I am experiencing some difficulties and would very much like your advice and help.

I am considering ways to reduce the number of attention computations. In my setup, I have a 2D tensor with a shape of [N,H,W,C]. Additionally, I possess a mask with data type 'bool' and a shape of [N,H,W,1], which indicates valid positions in the tensor if the value is 1. 

To reduce the attention computations, one idea I have is to exclude pixels from positions where mask=0 from being qkv in the calculations, thereby lowering computational complexity. I am unsure if this can be implemented in NA and would love to hear your thoughts. Any advice would be incredibly helpful to me. Thanks for your time!

**Comment by alihassanijr** [comment]
Thank you for your interest.

I may have misunderstood, but it appears you're referring to token/pixel masking, and not attention masking.
The difference is in the mask itself. Attention masking is typically masking interactions between tokens (edges in the attention graph) and not the tokens themselves (nodes in the attention graph). In other words, with attention masking your boolean mask tensor would be of shape [N, HW, HW].

In your case, which requires pixel masking, here's a few options:

You could use the mask to filter out masked tokens before you do the QKV projection, creating a new smaller tensor that you send through the attention module.
However, I wouldn't always expect a visible improvement in speed / memory usage, which is the primary concern for most, not unless you're masking a large enough ratio of the tokens available.
The reason for that is a bit complicated, but it comes down to this: your problem size (shape of your input and weight tensors) is what determines how resources are allocated, and due to a number of reasons, reducing your problem size does not always result in improved speed, because resource allocation and the type of the problem play a larger hand in observable latency than the slight change in problem size. (If you'd like me to get into more details on this please let me know.)

As for whether NA is going to be applicable or not, it depends on your problem.
You can still use 1-D NA for most problems, but if you're in 2-D, it would depend on whether you're still maintaining the 2-D spatial structure. If that is the case, you can still use 2-D NA as well.

If you're generally interested in efficiency, it's a good idea to also look at the rest of your architecture. Depending on your setting, and the number of tokens you're dealing with, your model could be bottlenecked by linear projections instead of attention.

I hope this answers your question, but feel free to keep the issue open and ask more if that's not the case.

**Comment by yifanlu0227** [comment]
Thank you very much for your detailed response! Your insights have been incredibly helpful. I'd like to further clarify my settings and would appreciate your input on this matter.

Yes, I'm working with pixel masking. In my feature map mask, approximately 20% of the pixels are valid. Based on your advice, I plan to first apply the mask to the feature map, perform the qkv linear transformation only on the valid values, and then scatter them back to the 2D spatial shape to execute `natten2dqkrpb` and `natten2dav`. This should reduce some of the computational complexity, and still use 2D NA. Within `natten2dqkrpb` and `natten2dav`, is it possible to further reduce the computational complexity? 

Thanks again!

**Comment by alihassanijr** [comment]
Yes, NA's complexity is linear with respect to kernel size, number of pixels, dimensions, and batch size (and number of heads).

Reducing any of those will reduce complexity linearly.

In this case, you're already reducing the number of pixels with masking, you might be able to reduce complexity further by using a smaller kernel size.

However, I'll again note that all of this is theoretical, and in some settings you may not necessarily observe any improvement.

If you're using 2D NA, I'd --strongly-- encourage setting the dims per head to 32, because NATTEN has tiled kernels for dim=32 which means they will run a lot faster.

If your GPU architecture is Ampere or newer, I'd also highly recommend trying the latest release on the main branch by building from source; our new GEMM kernels can give you up to 10X throughput improvement.

**Comment by yifanlu0227** [comment]
Great! Thank you for your considerable response!
