### ISSUE TITLE
About the parameter settings of the NeighborhoodAttention2D module

### ISSUE THREAD

**Issue by CodeStarting-design** [SHI-Labs/NATTEN#44]
Could you please explain the meaning of dilation, window_size, and kernel_size in the NeighborhoodAttention2D module? It is observed that when calculating neighbor attention, only the dilation parameter needs to be passed. Does this parameter represent the neighborhood size?

**Comment by alihassanijr** [comment]
Thanks for your interest.

Kernel size and dilation are user-specified parameters. A kernel size of 7 (7x7) means each query will attend to exactly 7x7=49 of its nearest neighbors. Dilation increases the step size between neighbors. For more information I'd refer you to our papers.

As for the implementation, it is true that up until a few months ago, the API only took in the tensors and a dilation value; and this is simply because relative positional biases were required back then, and their shape gives you kernel size.

**Comment by CodeStarting-design** [comment]
Thanks for your reply and great job!

**Comment by alihassanijr** [comment]
Closing this now; feel free to reopen if you have more questions.
