### ISSUE TITLE
how to implement the kernel size 1X3 or 3X1 NAT layer like conv layer?

### ISSUE THREAD

**Issue by verigle** [SHI-Labs/NATTEN#49]
how to implement the kernel size 1X3 or 3X1 NAT layer like conv layer?

**Comment by alihassanijr** [comment]
You can use the 1D modules instead of 2D, it will be identical, but would probably require you to do a reshape. 
Unfortunately our kernels do not support non-square kernel sizes yet.

However, note that in general and as of now, our 1D GEMM kernels are going to be considerably faster than any of our other kernels, even when looking at equal-sized attention maps (i.e. 1D NA with kernel size 49 is faster than 2D NA with kernel size 7x7 == 49; as long as you're using GEMM).

**Comment by verigle** [comment]
thank you

**Comment by alihassanijr** [comment]
Closing this now; feel free to reopen if you have more questions.
