### ISSUE TITLE
Comparison to FlashAttention

### ISSUE THREAD

**Issue by kklemon** [SHI-Labs/NATTEN#51]
Hi, and thanks for this great project.

I was curious if NATTEN incorporates any of the hardware optimizations from [FlashAttention](https://github.com/Dao-AILab/flash-attention). How does its performance compare to FA for a give set of (comparable) hyperparameters? The [paper](https://arxiv.org/pdf/2209.15001.pdf) only mentions FA in a sidenote, but I believe that the general approach should be applicable to neighborhood attention as well. However, I understand that introducing such low-level optimizations can be challenging and time-intensive.

**Comment by alihassanijr** [comment]
Thank you for your interest.

You are right in that kernel fusion for neighborhood attention is possible, and we intend to write such kernels in the near future. It's just hard to estimate exactly when that will be, because ideally we'd like to write everything from scratch using CUTLASS 3 and CUTE (similar to FAv2), and not only does that take time, we're also blocked by a few other requirements to do it right. But again we fully intend to start working on that soon.

And yes, the theory perfectly checks out, and a kernel fusion for NA is possible without adding extra computation (just a bit of extra indexing logic on older gen GPUs.)

I hope this answers your question.

**Comment by alihassanijr** [comment]
Closing this; feel free to reopen if you still have questions.
