### ISSUE TITLE
How to do full attention on one dimension, while neighbor Attention on another 2 dimensions?

### ISSUE THREAD

**Issue by confucianism72** [SHI-Labs/NATTEN#67]
Hello, I am trying to  do full attention on one dimension and  Neighbor Attention on another two dimensions in 3D cases.

take an example, my full tensor has shape (channel, x, y), I want my token attend all tokens in its neighborhood, then the window has size (channel, 3, 3).

How can I do this using NATTEn?

Thanks

**Comment by confucianism72** [comment]
Now I know it, just set dilation_d == # channels.

**Comment by confucianism72** [comment]
# looking forward to GEMM-based 3D NA operators.

**Comment by alihassanijr** [comment]
Thank you for your interest; yes you are correct, the way to achieve this would be with 3D NA. However, I think there might be an easier way to formulate it, because even 2D GEMM based NA still isn't as flexible in terms of your choice of kernel size, let alone our future 3D GEMM based kernels.

That said, I'm coming back to working on this project with more time in the coming weeks, so we'll definitely be seeing more improvements to NATTEN in the next few months.

**Comment by confucianism72** [comment]
Thanks for reply.

by the way

> just set dilation_d == # channels.

A typo I made, now I think 
```kernel_size_d = # channels.```

**Comment by confucianism72** [comment]
After my experiment, doing this (kernel_size_d = # channels in 3D) seems consumes a lot of memory.

I am seeking how to improve this.

**Comment by confucianism72** [comment]
Suppose C = # channels, I think using natten2dav, natten2dqkrpb for $C^2$ times may be a good alternative.

But I am not familiar with cuda program.

I plan to try it using pure python and read details about tiled NA algorithm

**Comment by alihassanijr** [comment]
Sorry for the delay in my response (again).

I'd first clarify that `kernel_size_d` should be equal to whatever the dimension size is. If you're attending across channels, then it would be channels, otherwise, I think it should be different.

As for memory usage, unfortunately that's unavoidable at the moment given that NATTEN still doesn't have any fused kernels available, and the 3D variant would be an extra challenge. If the memory usage is so bad that you can't experiment with it, unfortunately the only solution is to just reduce kernel size at the moment. 3D has always been a challenge, and we don't even have a tiled kernel for it, let alone GEMM-based. Although both tiled and GEMM-based, and even fused are possible in theory, it's just a lot of work to write all of them, and I've been away from the project for a while. However, as I said, once I get back, new and more optimized kernels are at the top of my list.

I'd highly recommend not using a pure python implementation; the reason why NA is written as CUDA kernels directly is exactly that pure python implementations will introduce a great deal of overhead. It will basically be like writing your own convolution. (Although none of these are pure python, they're just different levels of abstraction in python -- most DL primitives are written in C/C++ or other such languages and heavily perf optimized.)

**Comment by confucianism72** [comment]
Thank you Ali. I have learned a lot from your work. I just started learning cuda programming.
