### ISSUE TITLE
The kernel size of 2d NATTEN

### ISSUE THREAD

**Issue by RayTan183** [SHI-Labs/NATTEN#77]
I noticed that the maxinum supported kernel size is 13. Will the version in the future support larger kernel size, such as 15 or even 31 ?

**Comment by alihassanijr** [comment]
Thank you for your interest;

We already support larger kernel sizes; it's just not included in the latest release. You'll have to install NATTEN from source to get those.

Our naive kernels support arbitrary sized kernels, and our GEMM kernels support up to 33x33. We don't support larger kernels now because 2D kernel sizes are templated, and we only instantiate up to 33x33 to allow the library to compile within a reasonable amount of time.

**Comment by RayTan183** [comment]
Thank you for your contribution. I have installed NATTEN from source and it works. But i am so curious that why the params will not change with the larger kernel size. I use `thop` to measure the params.

**Comment by alihassanijr** [comment]
Attention does not have learnable parameters (unless attention bias is enabled, and even then it's very minute). FLOPs will change with kernel size.

**Comment by alihassanijr** [comment]
I'm sorry, I don't think I understand. Did the number of parameters increase or not? What specifically do you mean by model size?

**Comment by RayTan183** [comment]
I try to train my model with different kernel sizes. When the kernel size is 13, the model side is 2.43M. After changing the kernel size to 31, the model size is 2.93M.

**Comment by alihassanijr** [comment]
That's normal; it should be the positional biases that result in the slight change in parameters.
If you disable bias, parameter counts should be identical.

**Comment by RayTan183** [comment]
I get it. Thank for your reply !

**Comment by alihassanijr** [comment]
Closing this now; feel free to reopen if you still have questions.
