### ISSUE TITLE
Using NeighborhoodAttention2D In YOLO

### ISSUE THREAD

**Issue by KulikDM** [SHI-Labs/NATTEN#84]
Hi, I've been trying to use NeighborhoodAttention2D in the YOLO framework. This was done by inserting components either in the end of the backbone or in one of the head portions. There has been marginal success, in that it works, but not really seeing any benefits from my implementation. Do you have any suggestions on what might be the optimal/suggested way to incorporate NeighborhoodAttention2D into the YOLO framework?

**Comment by alihassanijr** [comment]
Thank you for your interest.

Unfortunately I can't really speak to that; it's a matter of architecture search and there's just a lot of hyperparameters one could search over. It can be somewhat difficult to plug NA, and more generally attention, into an architecture and get visible performance improvements. Plugging NA into detection models directly (and not through a backbone network that has NA) is even more challenging due to the fact that there's few baselines that consider self attention in detection models from which we could start.

If you're referring to latency / speed, given that NATTEN is still an experimental project and not performance optimized as well as the rest of the components in a model, I wouldn't really expect much. That said, we are working to optimize the performance of our kernels further.

**Comment by KulikDM** [comment]
@alihassanijr thank you for your response, this makes sense. l'll continue to experiment with different architectures. Perhaps some interesting results may come from it. Will make sure to post it here if I do ;)
